name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci-checks.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
